name: Publish Olive Packages

on:
  push:
    branches: [ main ]
    
jobs:
 build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest

    steps:
      - name: Check out Repo
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Pack
        run: dotnet pack Olive.Microservices.Hub.csproj -c Release

      - name: Publish to GitHub packages 
        run: dotnet nuget push /home/runner/work/Olive.Microservices.Hub/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate`
